version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: shopsphere-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: shopsphere
      POSTGRES_USER: morgan
      POSTGRES_PASSWORD: morgan

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: